---
galaxy_info:
  author: George Miroshnykov
  description: provision Node.js app
  min_ansible_version: 1.4
  version: 0.2.0
  platforms:
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
  - web
# dependencies:
  # - laggyluke.nodejs
  # - laggyluke.direnv
