---
- name: Install Kraftwagen Drush module.
  git: >
    repo={{ drupal_kw_source }}
    version={{ drupal_kw_source_branch }}
    accept_hostkey=yes
    dest=/home/{{ drupal_www_owner }}/.drush/kraftwagen
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"

- name: Clear the Drush cache.
  command: >
    /usr/local/bin/drush cc drush
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"

- name: Check if Drupal is booting.
  shell: >
    /usr/local/bin/drush status | grep -e "Drupal bootstrap.*\:.*Successful"
    chdir={{ drupal_path }}
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"
  register: drupal_is_booting
  ignore_errors: True

- name: Check if the src directory is already there.
  stat: "path={{ drupal_project_path }}/src"
  register: drupal_project_destination_status

# Project from Git.
- name: Add project from Git.
  include: git.yml
  when: drupal_source | match("^(git|ssh|(http(s)?)).+\.git$")
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"

- name: Ensure Drupal project directory exist.
  file:
    path: "{{ drupal_project_path }}"
    state: directory
    owner: "{{ drupal_www_owner }}"
    group: "{{ drupal_www_owner }}"
  ignore_errors: True
  

# New project.
- name: Create new Kraftwagen project.
  command: >
    /usr/local/bin/drush kw-np
      --skeleton={{ drupal_kw_skeleton_source }}
      --branch={{ drupal_kw_skeleton_branch }}
      --name={{ drupal_kw_name }}
      --human-name="{{ drupal_kw_human_name }}"
    chdir={{ drupal_project_path }}
    creates={{ drupal_project_path }}/src/{{ drupal_kw_name }}.profile
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"
  when: drupal_project_destination_status.stat.exists == false

# Setup the project.
- name: Setup the new Kraftwagen project.
  command: >
    /usr/local/bin/drush kw-setup --env={{ drupal_env }}
    chdir={{ drupal_project_path }}
    creates={{ drupal_project_path }}/cnf
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"

# Build the project.
- name: Build the Kraftwagen project.
  command: >
    /usr/local/bin/drush kw-b
    chdir={{ drupal_project_path }}
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"

- name: Set permissions properly to the files directory.
  file: >
    path={{ drupal_project_path }}/cnf/files
    mode=6775
    owner={{ drupal_www_owner }}
    group={{ drupal_www_group }}
    state=directory
    recurse=yes
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"
  ignore_errors: True

# Drupal Settings files.
- include: settings.php.yml
  sudo: yes
  when: drupal_is_booting.rc != 0

# Install the Drupal via drush.
- name: Install Drupal.
  command: >
    /usr/local/bin/drush si -y {{ drupal_kw_name }}
    --site-name="{{ drupal_site_name }}"
    --account-name="{{ drupal_admin_name }}"
    --account-pass={{ drupal_admin_password }}
    --db-url={{ drupal_db.driver }}://{{ drupal_db.user }}:{{ drupal_db.password }}@{{ drupal_db.host }}/{{ drupal_db.database }}
    chdir={{ drupal_path }}
  register: drupal_new_installation_result
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"
  when: >
    drupal_is_booting.rc != 0
    and drupal_db.database != "" and drupal_db.host != ""
  notify:
    - drupal kraftwagen manifests

# Permissions.
- name: Set permissions for the Drupal root path directory.
  file: >
    path={{ drupal_path }} mode=6775
    owner={{ drupal_www_owner }} group={{ drupal_www_group }}
    state=directory
  ignore_errors: True

- name: Krafwagen will run all the manifests.
  command: >
    drush kw-m
    chdir={{ drupal_path }}
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"
