_core:
  default_config_hash: zJZgLt2aMx8kcz6-dWZYBbF-kRi7558TkK_x3wzK3u8
format: endnote8
types:
  'Aggregated Database': ''
  'Ancient Text': ''
  Artwork: ''
  'Audiovisual Material': audiovisual
  Bill: bill
  Blog: ''
  Book: book
  'Book Section': book_chapter
  Case: case
  Catalog: ''
  'Chart or Table': chart
  'Classical Work': classical
  'Computer Program': software
  'Conference Paper': conference_paper
  'Conference Proceedings': conference_proceedings
  Dataset: ''
  Dictionary: ''
  'Edited Book': book
  'Electronic Article': web_article
  'Electronic Book Section': ''
  Encyclopedia: ''
  Equation: ''
  Figure: ''
  'Film or Broadcast': film
  Generic: ''
  'Government Document': government_report
  Grant: ''
  Hearing: hearing
  'Journal Article': journal_article
  'Legal Rule or Regulation': legal_ruling
  'Magazine Article': magazine_article
  Manuscript: manuscript
  Map: map
  Music: ''
  'Newspaper Article': newspaper_article
  'Online Database': database
  'Online Multimedia': ''
  Pamphlet: ''
  Patent: patent
  'Personal Communication': personal
  Report: report
  Serial: ''
  Standard: ''
  Statute: statute
  Thesis: thesis
  'Unpublished Work': unpublished
  'Web Page': website
fields:
  title: title
  authors: author
  secondary-title: bibcite_secondary_title
  tertiary-title: bibcite_tertiary_title
  alt-title: bibcite_alternate_title
  short-title: bibcite_short_title
  translated-title: bibcite_translated_title
  full-title: ''
  rec-number: ''
  urls: bibcite_url
  ref-type: type
  year: bibcite_year
  date: bibcite_date
  keyword: keywords
  access-date: bibcite_access_date
  accession-num: bibcite_accession_number
  auth-address: bibcite_auth_address
  electronic-resource-num: bibcite_doi
  pages: bibcite_pages
  volume: bibcite_volume
  issue: bibcite_issue
  edition: bibcite_edition
  number: bibcite_number
  section: bibcite_section
  abstract: bibcite_abst_e
  isbn: bibcite_isbn
  label: bibcite_label
  caption: ''
  publisher: bibcite_publisher
  pub-location: bibcite_place_published
  language: bibcite_lang
  notes: bibcite_notes
  research-notes: bibcite_research_notes
  remote-database-provider: bibcite_remote_db_provider
  remote-database-name: bibcite_remote_db_name
  work-type: bibcite_type_of_work
  custom1: bibcite_custom1
  custom2: bibcite_custom2
  custom3: bibcite_custom3
  custom4: bibcite_custom4
  custom5: bibcite_custom5
  custom6: bibcite_custom6
  custom7: bibcite_custom7
indexes:
  'Aggregated Database': '55'
  'Ancient Text': '51'
  Artwork: '2'
  'Audiovisual Material': '3'
  Bill: '4'
  Blog: '56'
  Book: '6'
  'Book Section': '5'
  Case: '7'
  Catalog: '8'
  'Chart or Table': '38'
  'Classical Work': '49'
  'Computer Program': '9'
  'Conference Paper': '47'
  'Conference Proceedings': '10'
  Dataset: '59'
  Dictionary: '52'
  'Edited Book': '28'
  'Electronic Article': '43'
  'Electronic Book Section': '60'
  Encyclopedia: '53'
  Equation: '39'
  Figure: '37'
  'Film or Broadcast': '21'
  Generic: '13'
  'Government Document': '46'
  Grant: '54'
  Hearing: '14'
  'Journal Article': '17'
  'Legal Rule or Regulation': '50'
  'Magazine Article': '19'
  Manuscript: '36'
  Map: '20'
  Music: '61'
  'Newspaper Article': '23'
  'Online Database': '45'
  'Online Multimedia': '48'
  Pamphlet: '24'
  Patent: '25'
  'Personal Communication': '26'
  Report: '27'
  Serial: '57'
  Standard: '58'
  Statute: '31'
  Thesis: '32'
  'Unpublished Work': '34'
  'Web Page': '12'
dependencies:
  enforced:
    module:
      - bibcite_endnote
