_core:
  default_config_hash: wH40znhdAqFaoXVoSEc3m3byPL7h68yeKKdYtXUi-no
embed_provider: 'http://ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}'
ckeditor_version: ''
plugins_installed_version: ''
