id: node.pece_artifact_fieldnote.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_artifact_fieldnote
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 948fa36f-efbb-41ce-a284-cb18de689e2f
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_artifact_fieldnote
