id: media.audio.media_library
targetEntityType: media
bundle: audio
mode: media_library
content:
  thumbnail:
    type: image
    label: hidden
    settings:
      image_link: ''
      image_style: medium
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  field_media_audio_file: true
  langcode: true
  name: true
  search_api_excerpt: true
  uid: true
uuid: e911787c-d36a-46d6-ac1f-1820035899e2
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.media_library
    - field.field.media.audio.field_media_audio_file
    - image.style.medium
    - media.type.audio
  module:
    - image
_core:
  default_config_hash: cae-gnA0C0B2NMxMwAp04tRkomTuMvWRPuArT8aZI3g
