id: bibcite_reference.newspaper_article.default
targetEntityType: bibcite_reference
bundle: newspaper_article
mode: default
status: true
content:
  author:
    type: bibcite_contributor_widget
    weight: 3
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_accession_number:
    type: string_textfield
    weight: 34
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_call_number:
    type: string_textfield
    weight: 35
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_date:
    type: string_textfield
    weight: 26
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_doi:
    type: string_textfield
    weight: 39
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_edition:
    type: string_textfield
    weight: 20
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_isbn:
    type: string_textfield
    weight: 33
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_issn:
    type: string_textfield
    weight: 32
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_number:
    type: string_textfield
    weight: 24
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_number_of_volumes:
    type: string_textfield
    weight: 23
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_original_publication:
    type: string_textfield
    weight: 45
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_other_number:
    type: string_textfield
    weight: 36
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_pages:
    type: string_textfield
    weight: 25
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_place_published:
    type: string_textfield
    weight: 31
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_pmcid:
    type: string_textfield
    weight: 52
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_pmid:
    type: string_textfield
    weight: 52
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_refereed:
    type: string_textfield
    weight: 51
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_reprint_edition:
    type: string_textfield
    weight: 29
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_secondary_title:
    type: string_textfield
    weight: 18
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_section:
    type: string_textfield
    weight: 21
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_short_title:
    type: string_textfield
    weight: 42
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_type_of_work:
    type: string_textfield
    weight: 27
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_url:
    type: string_textfield
    weight: 38
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_volume:
    type: string_textfield
    weight: 19
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_year:
    type: number
    weight: 17
    region: content
    settings:
      placeholder: ''
    third_party_settings: {  }
  keywords:
    type: entity_reference_autocomplete_tags
    weight: 4
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 120
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: 2
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 100
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden:
  bibcite_abst_e: true
  bibcite_abst_f: true
  bibcite_access_date: true
  bibcite_alternate_title: true
  bibcite_auth_address: true
  bibcite_citekey: true
  bibcite_custom1: true
  bibcite_custom2: true
  bibcite_custom3: true
  bibcite_custom4: true
  bibcite_custom5: true
  bibcite_custom6: true
  bibcite_custom7: true
  bibcite_issue: true
  bibcite_label: true
  bibcite_lang: true
  bibcite_notes: true
  bibcite_other_author_affiliations: true
  bibcite_publisher: true
  bibcite_remote_db_name: true
  bibcite_remote_db_provider: true
  bibcite_research_notes: true
  bibcite_tertiary_title: true
  bibcite_translated_title: true
uuid: 12506109-024d-4e03-8224-003d172ee321
langcode: en
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.newspaper_article
  module:
    - bibcite_entity
