id: taxonomy_term.groups.default
targetEntityType: taxonomy_term
bundle: groups
mode: default
status: true
content:
  description:
    type: text_textarea
    weight: 2
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
  field_group_managers:
    type: entity_reference_autocomplete
    weight: 6
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_group_members:
    type: entity_reference_autocomplete
    weight: 5
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_group_visibility:
    type: options_select
    weight: 3
    region: content
    settings: {  }
    third_party_settings: {  }
  field_image:
    type: media_library_widget
    weight: 1
    region: content
    settings:
      media_types:
        - private_image
        - private_vector_image
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
      media_library_edit:
        show_edit: '1'
        edit_form_mode: default
  field_substantive_logic:
    type: entity_reference_autocomplete
    weight: 4
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_tags:
    type: entity_reference_autocomplete
    weight: 7
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  path:
    type: path
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  tvi:
    weight: 100
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  field_pece_project_ref: true
  langcode: true
  status: true
uuid: 2c489e82-e196-421a-9bb5-a9a4e2e1eba7
langcode: en
dependencies:
  config:
    - field.field.taxonomy_term.groups.field_group_managers
    - field.field.taxonomy_term.groups.field_group_members
    - field.field.taxonomy_term.groups.field_group_visibility
    - field.field.taxonomy_term.groups.field_image
    - field.field.taxonomy_term.groups.field_pece_project_ref
    - field.field.taxonomy_term.groups.field_substantive_logic
    - field.field.taxonomy_term.groups.field_tags
    - taxonomy.vocabulary.groups
  module:
    - entity_form_field_label
    - media_library
    - media_library_edit
    - path
    - text
