id: node.pece_project.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_project
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 52102212-642f-4a46-9cdf-096d7089b489
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_project
