id: media.audio.default
targetEntityType: media
bundle: audio
mode: default
status: true
content:
  created:
    type: datetime_timestamp
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  field_media_audio_file:
    type: file_generic
    weight: 0
    region: content
    settings:
      progress_indicator: throbber
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: -5
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 100
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 5
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden: {  }
uuid: 36ae3c06-5bdb-4762-a4e8-4d001be25882
langcode: en
dependencies:
  config:
    - field.field.media.audio.field_media_audio_file
    - media.type.audio
  module:
    - file
    - path
_core:
  default_config_hash: 9vliOuE44vj_lkRIg22ki4Ro6HXRL-uGUSORGb62xwQ
