id: node.pece_essay.intro_page
targetEntityType: node
bundle: pece_essay
mode: intro_page
content:
  body:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  extra_field_pece_annotations_annotate_button:
    type: extra_field_pece_annotations_annotate_button
    settings: {  }
    third_party_settings: {  }
    weight: 4
    region: content
  extra_field_pece_annotations_see_annotations_link:
    type: extra_field_pece_annotations_see_annotations_link
    settings: {  }
    third_party_settings: {  }
    weight: 5
    region: content
  extra_field_pece_essays_essay_link:
    type: extra_field_pece_essays_essay_link
    settings: {  }
    third_party_settings: {  }
    weight: 3
    region: content
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 1
    region: content
  field_cite_as:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 9
    region: content
  field_groups_with_view_access:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 7
    region: content
  field_media_thumbnail:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: card
      link: false
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
      fences:
        fences_field_tag: div
        fences_field_classes: ''
        fences_field_items_wrapper_tag: none
        fences_field_items_wrapper_classes: ''
        fences_field_item_tag: none
        fences_field_item_classes: ''
        fences_label_tag: none
        fences_label_classes: ''
    weight: 2
    region: content
  field_pece_license:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 11
    region: content
  field_pece_project_ref:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 10
    region: content
  field_people_with_edit_access:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 6
    region: content
  field_tags:
    type: entity_reference_label
    label: inline
    settings:
      link: true
    third_party_settings: {  }
    weight: 8
    region: content
hidden:
  extra_field_pece_essays_intro_link: true
  field_analyze: true
  field_ark_enabled: true
  field_conceptualize: true
  field_curate: true
  field_essay_contents: true
  field_legacy_rendered_html: true
  field_override_legacy_with_new: true
  field_pece_all_can_view: true
  field_pece_artifacts: true
  field_people_with_view_access: true
  langcode: true
  layout_builder__layout: true
  links: true
  search_api_excerpt: true
uuid: 26c95ea8-8040-4c5c-9c9e-d5e18cdb87ca
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.intro_page
    - field.field.node.pece_essay.body
    - field.field.node.pece_essay.field_analyze
    - field.field.node.pece_essay.field_ark_enabled
    - field.field.node.pece_essay.field_cite_as
    - field.field.node.pece_essay.field_conceptualize
    - field.field.node.pece_essay.field_curate
    - field.field.node.pece_essay.field_essay_contents
    - field.field.node.pece_essay.field_groups_with_view_access
    - field.field.node.pece_essay.field_legacy_rendered_html
    - field.field.node.pece_essay.field_media_thumbnail
    - field.field.node.pece_essay.field_override_legacy_with_new
    - field.field.node.pece_essay.field_pece_all_can_view
    - field.field.node.pece_essay.field_pece_artifacts
    - field.field.node.pece_essay.field_pece_license
    - field.field.node.pece_essay.field_pece_project_ref
    - field.field.node.pece_essay.field_people_with_edit_access
    - field.field.node.pece_essay.field_people_with_view_access
    - field.field.node.pece_essay.field_tags
    - field.field.node.pece_essay.layout_builder__layout
    - node.type.pece_essay
  module:
    - entity_form_field_label
    - fences
    - layout_builder
    - text
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: HMSXo2f0tj9lPu_qSfMVAOMgO9tTZLm53p6zRWL1WgM
