_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
