id: media.full
label: 'Full content'
description: ''
targetEntityType: media
cache: true
uuid: 763471ce-8aaa-4c83-bd66-a504a452250c
langcode: en
status: false
dependencies:
  module:
    - media
_core:
  default_config_hash: 6NBUEuGmlkClK8Fb76tSMMpO2eZ4LWCBdbUk4z7CuP0
