id: media.media_library
label: 'Media library'
description: ''
targetEntityType: media
cache: true
uuid: 093253f8-dbd7-4575-be3b-330e274de671
langcode: en
status: true
dependencies:
  module:
    - media
  enforced:
    module:
      - media_library
_core:
  default_config_hash: Tdhz-aDHfDoV1Ul9umtItxGTrjkFzoNAkDw8FWXjYA0
