id: taxonomy_term.groups.default
targetEntityType: taxonomy_term
bundle: groups
mode: default
content:
  description:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_group_managers:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 5
    region: content
  field_group_members:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 4
    region: content
  field_group_visibility:
    type: list_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 2
    region: content
  field_image:
    type: entity_reference_entity_view
    label: above
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
    weight: 7
    region: one_a
  field_pece_project_ref:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 1
    region: content
  field_substantive_logic:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 3
    region: content
  field_tags:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 6
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
uuid: d11deb4e-d300-4cfe-a7d8-ef6d16bd0ea7
langcode: en
status: true
dependencies:
  config:
    - field.field.taxonomy_term.groups.field_group_managers
    - field.field.taxonomy_term.groups.field_group_members
    - field.field.taxonomy_term.groups.field_group_visibility
    - field.field.taxonomy_term.groups.field_image
    - field.field.taxonomy_term.groups.field_pece_project_ref
    - field.field.taxonomy_term.groups.field_substantive_logic
    - field.field.taxonomy_term.groups.field_tags
    - taxonomy.vocabulary.groups
    - views.view.group_artifacts
    - views.view.group_essays
    - views.view.group_field_notes
    - views.view.group_memos
  module:
    - layout_builder
    - layout_collapse
    - layout_library
    - options
    - text
    - views
third_party_settings:
  layout_builder:
    enabled: true
    allow_custom: false
    sections:
      -
        layout_id: layout_collapse_twocol_section
        layout_settings:
          label: ''
          one_a:
            layout_collapse_element: layout-collapse--none
            layout_collapse_classes: ''
            layout_collapse_summary: ''
          one_b:
            layout_collapse_element: layout-collapse--closed
            layout_collapse_classes: ''
            layout_collapse_summary: 'Group Artifacts'
          one_c:
            layout_collapse_element: layout-collapse--closed
            layout_collapse_classes: ''
            layout_collapse_summary: 'Group Field Notes'
          one_d:
            layout_collapse_element: layout-collapse--closed
            layout_collapse_classes: ''
            layout_collapse_summary: 'Group Memos'
          one_e:
            layout_collapse_element: layout-collapse--closed
            layout_collapse_classes: ''
            layout_collapse_summary: 'Group Essays'
          two_a:
            layout_collapse_element: layout-collapse--none
            layout_collapse_classes: ''
            layout_collapse_summary: ''
          two_b:
            layout_collapse_element: layout-collapse--open
            layout_collapse_classes: ''
            layout_collapse_summary: 'Group Manager(s)'
          two_c:
            layout_collapse_element: layout-collapse--closed
            layout_collapse_classes: ''
            layout_collapse_summary: 'Group Members'
          two_d:
            layout_collapse_element: layout-collapse--none
            layout_collapse_classes: ''
            layout_collapse_summary: ''
          two_e:
            layout_collapse_element: layout-collapse--none
            layout_collapse_classes: ''
            layout_collapse_summary: ''
          layout_collapse_two_column_widths: layout--twocol-section--67-33
          layout_collapse_classes: ''
          context_mapping: {  }
        components:
          acb9426f-a94c-45ee-a0eb-0ae4fece0c56:
            uuid: acb9426f-a94c-45ee-a0eb-0ae4fece0c56
            region: one_a
            configuration:
              id: 'field_block:taxonomy_term:groups:description'
              label: Description
              label_display: '0'
              provider: layout_builder
              context_mapping:
                entity: layout_builder.entity
                view_mode: view_mode
              formatter:
                type: text_default
                label: hidden
                settings: {  }
                third_party_settings:
                  entity_form_field_label:
                    new_label: ''
                    rewrite_label: 0
            weight: 1
            additional: {  }
          0ab3d34f-9956-4d1a-9531-1da6b5859db5:
            uuid: 0ab3d34f-9956-4d1a-9531-1da6b5859db5
            region: one_a
            configuration:
              id: 'field_block:taxonomy_term:groups:field_substantive_logic'
              label: 'Substantive Logics'
              label_display: visible
              provider: layout_builder
              context_mapping:
                entity: layout_builder.entity
                view_mode: view_mode
              formatter:
                type: entity_reference_label
                label: hidden
                settings:
                  link: true
                third_party_settings:
                  entity_form_field_label:
                    new_label: ''
                    rewrite_label: 0
            weight: 2
            additional: {  }
          aab36e57-102f-44d4-9c9b-3a81740efb2f:
            uuid: aab36e57-102f-44d4-9c9b-3a81740efb2f
            region: one_b
            configuration:
              id: 'views_block:group_artifacts-block_1'
              label: ''
              label_display: '0'
              provider: views
              context_mapping: {  }
              views_label: ''
              items_per_page: none
            weight: 3
            additional: {  }
          8e216fce-108f-4795-80bd-d7607df323a0:
            uuid: 8e216fce-108f-4795-80bd-d7607df323a0
            region: one_c
            configuration:
              id: 'views_block:group_field_notes-block_1'
              label: ''
              label_display: '0'
              provider: views
              context_mapping: {  }
              views_label: ''
              items_per_page: none
            weight: 4
            additional: {  }
          efb984b8-1788-4e17-86b3-d4b1c015736e:
            uuid: efb984b8-1788-4e17-86b3-d4b1c015736e
            region: one_d
            configuration:
              id: 'views_block:group_memos-block_1'
              label: ''
              label_display: '0'
              provider: views
              context_mapping: {  }
              views_label: ''
              items_per_page: none
            weight: 5
            additional: {  }
          cf81124a-ea23-4573-9caf-aa52a620d652:
            uuid: cf81124a-ea23-4573-9caf-aa52a620d652
            region: one_e
            configuration:
              id: 'views_block:group_essays-block_1'
              label: ''
              label_display: '0'
              provider: views
              context_mapping: {  }
              views_label: ''
              items_per_page: none
            weight: 6
            additional: {  }
          84a50b24-da53-4e9f-82f3-84f885836f8b:
            uuid: 84a50b24-da53-4e9f-82f3-84f885836f8b
            region: two_d
            configuration:
              id: 'field_block:taxonomy_term:groups:field_tags'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              formatter:
                type: entity_reference_label
                label: above
                settings:
                  link: true
                third_party_settings: {  }
            weight: 0
            additional: {  }
          9858f00b-3c92-4fa1-a006-1f66a40aea35:
            uuid: 9858f00b-3c92-4fa1-a006-1f66a40aea35
            region: two_c
            configuration:
              id: 'field_block:taxonomy_term:groups:field_group_members'
              label: 'Group members'
              label_display: '0'
              provider: layout_builder
              context_mapping:
                entity: layout_builder.entity
                view_mode: view_mode
              formatter:
                type: entity_reference_label
                label: hidden
                settings:
                  link: true
                third_party_settings:
                  entity_form_field_label:
                    new_label: ''
                    rewrite_label: 0
            weight: 0
            additional: {  }
          bff48c25-c89e-4435-8803-0902ef07a55f:
            uuid: bff48c25-c89e-4435-8803-0902ef07a55f
            region: two_b
            configuration:
              id: 'field_block:taxonomy_term:groups:field_group_managers'
              label: 'Group manager(s)'
              label_display: '0'
              provider: layout_builder
              context_mapping:
                entity: layout_builder.entity
                view_mode: view_mode
              formatter:
                type: entity_reference_label
                label: hidden
                settings:
                  link: true
                third_party_settings:
                  entity_form_field_label:
                    new_label: ''
                    rewrite_label: 0
            weight: 0
            additional: {  }
          f08f2174-cecf-4227-8e3d-5930f7fc0181:
            uuid: f08f2174-cecf-4227-8e3d-5930f7fc0181
            region: two_a
            configuration:
              id: 'field_block:taxonomy_term:groups:field_image'
              label: Image
              label_display: '0'
              provider: layout_builder
              context_mapping:
                entity: layout_builder.entity
                view_mode: view_mode
              formatter:
                type: entity_reference_entity_view
                label: hidden
                settings:
                  view_mode: default
                third_party_settings:
                  entity_form_field_label:
                    new_label: ''
                    rewrite_label: 0
            weight: 0
            additional: {  }
        third_party_settings: {  }
  layout_library:
    enable: false
