id: node.pece_artifact_audio.field_authors
label: Creator(s)
field_name: field_authors
entity_type: node
bundle: pece_artifact_audio
description: 'This field designates the persor or people who originally created this artifact.  Creators known to the system will autocomplete; if this does not happen type the full name of a new creator and it will be added when this artifact is saved.'
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      pece_authors: pece_authors
    sort:
      field: name
      direction: asc
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
uuid: ea760feb-ac97-436b-99dc-e17e96cb7dc4
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_authors
    - node.type.pece_artifact_audio
    - taxonomy.vocabulary.pece_authors
_core:
  default_config_hash: saetGkxGRoFCJtYnE-zJxVflsRLZx-HQAZGws-1UZY4
