id: block_content.layout_block.body
label: Body
field_name: body
entity_type: block_content
bundle: layout_block
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: false
  required_summary: false
  allowed_formats: {  }
field_type: text_with_summary
uuid: ce05381d-bb10-439f-83fe-fe648046db74
langcode: en
status: true
dependencies:
  config:
    - block_content.type.layout_block
    - field.storage.block_content.body
  module:
    - text
