id: sidebar_right
label: 'Sidebar Right'
targetEntityType: node
targetBundle: pece_essay
layout:
  -
    layout_id: layout_twocol_section
    layout_settings:
      label: ''
      context_mapping: {  }
      column_widths: 67-33
    components: {  }
    third_party_settings: {  }
uuid: af62b94a-2395-4265-a293-8f1893d01138
langcode: en
status: true
dependencies: {  }
