_core:
  default_config_hash: lcQIEazCoV3xb72H67GTKBEuGmqBDkWVA6bm4Gb22NA
available_entities:
  node: node
  user: user
  asset: '0'
  block_content: '0'
  comment: '0'
  contact_message: '0'
  file: '0'
  flagging: '0'
  media: '0'
  shortcut: '0'
  taxonomy_term: '0'
  menu_link_content: '0'
  paragraph: '0'
