id: anonymous
label: 'Anonymous user'
weight: -10
is_admin: false
permissions:
  - 'access content'
  - 'use text format restricted_html'
  - 'view Terms and Conditions'
  - 'view any profile'
  - 'view empty pages'
  - 'view media'
  - 'view vocabulary labels'
uuid: 13713153-eb82-4cc1-9137-8d4e78cc4186
langcode: en
status: true
dependencies:
  config:
    - filter.format.restricted_html
  module:
    - empty_page
    - filter
    - legal
    - media
    - profile
    - system
    - taxonomy
_core:
  default_config_hash: Gl1lr_RJQ9pMz_DZhY6pNX94k874Gqh15Gm8Du1EepQ
