id: current_user_member_groups
label: 'Groups I am part of'
module: views
description: ''
tag: ''
base_table: taxonomy_term_field_data
base_field: tid
display:
  default:
    id: default
    display_title: Default
    display_plugin: default
    position: 0
    display_options:
      title: 'Groups I am part of'
      fields:
        name:
          id: name
          table: taxonomy_term_field_data
          field: name
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: taxonomy_term
          entity_field: name
          plugin_id: term_name
          label: ''
          exclude: false
          alter:
            alter_text: false
            make_link: false
            absolute: false
            word_boundary: false
            ellipsis: false
            strip_tags: false
            trim: false
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          convert_spaces: false
      pager:
        type: full
        options:
          offset: 0
          pagination_heading_level: h4
          items_per_page: 50
          total_pages: null
          id: 0
          tags:
            next: ››
            previous: ‹‹
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          quantity: 9
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      access:
        type: perm
        options:
          perm: 'access content'
      cache:
        type: tag
        options: {  }
      empty: {  }
      sorts:
        changed:
          id: changed
          table: taxonomy_term_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: taxonomy_term
          entity_field: changed
          plugin_id: date
          order: DESC
          expose:
            label: 'Updated date'
            field_identifier: changed
          exposed: false
          granularity: second
        created:
          id: created
          table: taxonomy_index
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: date
          order: DESC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
          granularity: second
      arguments:
        field_group_members_target_id:
          id: field_group_members_target_id
          table: taxonomy_term__field_group_members
          field: field_group_members_target_id
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: entity_target_id
          default_action: default
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: current_user
          default_argument_options: {  }
          summary_options:
            base_path: ''
            count: true
            override: false
            items_per_page: 25
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: true
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: false
          not: false
      filters:
        vid:
          id: vid
          table: taxonomy_term_field_data
          field: vid
          entity_type: taxonomy_term
          entity_field: vid
          plugin_id: bundle
          value:
            groups: groups
      style:
        type: html_list
      row:
        type: 'entity:taxonomy_term'
        options:
          relationship: none
          view_mode: search_result
      query:
        type: views_query
        options:
          query_comment: ''
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_tags: {  }
      relationships: {  }
      link_display: page
      link_url: ''
      header: {  }
      footer: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - user.permissions
      tags: {  }
  block:
    id: block
    display_title: Block
    display_plugin: block
    position: 2
    display_options:
      pager:
        type: some
        options:
          offset: 0
          items_per_page: 20
      sorts:
        changed:
          id: changed
          table: taxonomy_term_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: taxonomy_term
          entity_field: changed
          plugin_id: date
          order: DESC
          expose:
            label: 'Updated date'
            field_identifier: changed
          exposed: false
          granularity: second
        created:
          id: created
          table: taxonomy_index
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: date
          order: DESC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
          granularity: second
      defaults:
        pager: false
        use_more: false
        use_more_always: false
        use_more_text: false
        sorts: false
      use_more: true
      use_more_always: true
      use_more_text: 'See and sort all my joined groups'
      display_extenders:
        metatag_display_extender:
          metatags: {  }
          tokenize: false
      block_hide_empty: true
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - user
        - user.permissions
      tags: {  }
  page:
    id: page
    display_title: Page
    display_plugin: page
    position: 1
    display_options:
      sorts:
        changed:
          id: changed
          table: taxonomy_term_field_data
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: taxonomy_term
          entity_field: changed
          plugin_id: date
          order: DESC
          expose:
            label: 'Updated date'
            field_identifier: changed
          exposed: true
          granularity: second
        created:
          id: created
          table: taxonomy_index
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: date
          order: DESC
          expose:
            label: 'Created date'
            field_identifier: created
          exposed: true
          granularity: second
      defaults:
        sorts: false
      display_extenders:
        metatag_display_extender:
          metatags: {  }
          tokenize: false
      path: dashboard/pece/groups-joined
      use_admin_theme: true
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - 'url.query_args:sort_by'
        - 'url.query_args:sort_order'
        - user
        - user.permissions
      tags: {  }
uuid: acbae531-ea2b-4c0f-9260-5cb2885590ee
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.taxonomy_term.search_result
    - taxonomy.vocabulary.groups
  module:
    - taxonomy
    - user
