site_name: PECE Documentation
repo_url: https://github.com/PECE-project/pece-distro
nav:
   - Home: index.md
   - User's Guide: usersguide.md
   - Site Admin's Guide: siteadmin.md
   - System Admin's Guide: installation.md
   - Resources: legal.md
theme:
  name: null
  custom_dir: 'cinder'
extra_css:
  - "css/extra.css"
markdown_extensions:
  - admonition
  - markdown.extensions.extra
