---
galaxy_info:
  author: George Miroshnykov
  description: install direnv (http://direnv.net/)
  min_ansible_version: 1.4
  version: 2.5.0
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
